import type { Config } from "tailwindcss";

const v = (name: string) => `var(--${name})`;

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": v("on-background"),
        "surface-container": v("surface-container"),
        "surface-variant": v("surface-variant"),
        "outline-variant": v("outline-variant"),
        "error-container": v("error-container"),
        "surface-container-high": v("surface-container-high"),
        "on-error-container": v("on-error-container"),
        background: v("background"),
        "primary-container": v("primary-container"),
        "on-primary": v("on-primary"),
        "secondary-container": v("secondary-container"),
        error: v("error"),
        "surface-dim": v("surface-dim"),
        "inverse-on-surface": v("inverse-on-surface"),
        "surface-container-highest": v("surface-container-highest"),
        "inverse-primary": v("inverse-primary"),
        "primary-fixed": v("primary-fixed"),
        "on-primary-container": v("on-primary-container"),
        "surface-container-lowest": v("surface-container-lowest"),
        "tertiary-container": v("tertiary-container"),
        secondary: v("secondary"),
        "inverse-surface": v("inverse-surface"),
        outline: v("outline"),
        "on-secondary-container": v("on-secondary-container"),
        "surface-tint": v("surface-tint"),
        "surface-container-low": v("surface-container-low"),
        "on-error": v("on-error"),
        "primary-fixed-dim": v("primary-fixed-dim"),
        "on-secondary": v("on-secondary"),
        "on-tertiary": v("on-tertiary"),
        "on-surface-variant": v("on-surface-variant"),
        primary: v("primary"),
        surface: v("surface"),
        "surface-bright": v("surface-bright"),
        "on-primary-fixed": v("on-primary-fixed"),
        tertiary: v("tertiary"),
        "on-surface": v("on-surface"),
        "on-primary-fixed-variant": v("on-primary-fixed-variant"),
        positive: v("positive"),
        negative: v("negative"),
        neutral: v("neutral"),
        "card-bg": v("card-bg"),
        "card-border": v("card-border"),
        "canvas-bg": v("canvas-bg"),
        "primary-btn": v("primary-btn"),
        "input-bg": v("input-bg"),
      },
      borderRadius: {
        lg: "0.75rem",
        xl: "1rem",
        card: "20px",
        btn: "12px",
      },
      spacing: {
        "sidebar-width": "260px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        unit: "4px",
        gutter: "16px",
        "container-padding": "24px",
        "header-height": "64px",
      },
      fontFamily: {
        sans: ["Pretendard", "Inter", "Noto Sans KR", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-sm": ["19px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
      },
      boxShadow: {
        "deep-soft": "var(--shadow-soft)",
      },
    },
  },
  plugins: [],
};

export default config;
