import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#d8e3fb",
        "surface-container": "#152031",
        "surface-variant": "#2a3548",
        "outline-variant": "#424754",
        "error-container": "#93000a",
        "surface-container-high": "#1f2a3c",
        "on-error-container": "#ffdad6",
        background: "#081425",
        "primary-container": "#4d8eff",
        "on-primary": "#002e6a",
        "secondary-container": "#00a572",
        error: "#ffb4ab",
        "surface-dim": "#081425",
        "inverse-on-surface": "#263143",
        "surface-container-highest": "#2a3548",
        "inverse-primary": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "on-primary-container": "#00285d",
        "surface-container-lowest": "#040e1f",
        "tertiary-container": "#ff5451",
        secondary: "#4edea3",
        "inverse-surface": "#d8e3fb",
        outline: "#8c909f",
        "on-secondary-container": "#00311f",
        "surface-tint": "#adc6ff",
        "surface-container-low": "#111c2d",
        "on-error": "#690005",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary": "#003824",
        "on-tertiary": "#68000a",
        "on-surface-variant": "#c2c6d6",
        primary: "#adc6ff",
        surface: "#081425",
        "surface-bright": "#2f3a4c",
        "on-primary-fixed": "#001a42",
        tertiary: "#ffb3ad",
        "on-surface": "#d8e3fb",
        "on-primary-fixed-variant": "#004395",
        positive: "#10B981",
        negative: "#EF4444",
        neutral: "#64748B",
        "card-bg": "#1E293B",
        "card-border": "#334155",
        "canvas-bg": "#0F172A",
        "primary-btn": "#3B82F6",
        "input-bg": "#0F172A",
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        card: "12px",
        btn: "8px",
      },
      spacing: {
        "sidebar-width": "260px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        unit: "4px",
        gutter: "16px",
        "container-padding": "24px",
        "header-height": "64px",
      },
      fontFamily: {
        sans: ["Inter", "Noto Sans KR", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["10px", { lineHeight: "12px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      boxShadow: {
        "deep-soft": "0px 10px 15px -3px rgba(0, 0, 0, 0.5)",
      },
    },
  },
  plugins: [],
};

export default config;
